### ISSUE TITLE
How to  update an existing host instead of try to create?

### ISSUE THREAD

**Issue by agomerz** [Nosmoht/ansible-module-foreman#62]
I would like to be able to use this to create hostgroups and simply add instances to them.
The instances would already exist.
```
fatal: [ag-testanslb-1]: FAILED! => {"changed": false, "failed": true, "msg": "Could not create host: Name has already been taken"}
```

**Comment by Nosmoht** [comment]
Hi, did you try with FQDN or just hostname?

please post you action so I can try to reproduce it.

**Comment by mark-wagner** [comment]
Looking through the source code, `foreman_host.py` only supports updating host parameters, not other properties of hosts. In fact, the underlying module `foreman.py` does not define an `update_host()` function.
